import { useEffect, useMemo, useState } from "react";
import { Accessibility, ArrowLeftRight, BarChart3, BusFront, Check, CheckCircle2, CircleAlert, CreditCard, Database, FlaskConical, LayoutDashboard, Lightbulb, LockKeyhole, LogIn, LogOut, Map, MapPin, QrCode, Radio, RefreshCw, Route, Send, ShieldCheck, Smartphone, Ticket, UserRound, Users, WalletCards } from "lucide-react";

const API = "http://127.0.0.1:8000/api";
const roles = {
  rider: ["راكب", "احجز رحلة وتابع حالة طلبك"],
  driver: ["سائق", "راجع طلبات الصعود لخطوطك"],
  station: ["موظف محطة", "تابع الطلبات وخدمة الركاب"],
  ops: ["مركز التشغيل", "راقب مؤشرات الشبكة والطلبات"],
};

async function api(path, options = {}) {
  const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json" }, ...options });
  const data = await response.json();
  if (!response.ok) throw new Error(data.detail || "تعذر إتمام العملية.");
  return data;
}

function Brand() { return <div className="em-brand"><img src="/assets/masar-logo.png" alt="مسار | MASAR" /></div>; }

function PublicHome({ enter }) {
  return <div className="em-public" dir="rtl">
    <header className="em-public-header"><Brand /><nav><a href="#about">عن مسار</a><a href="#network">شبكة الخطوط</a><button onClick={enter}><LogIn size={17} />تسجيل الدخول</button></nav></header>
    <main>
      <section className="em-hero">
        <img src="/assets/eastern-region-home-banner.png" alt="حافلات المنطقة الشرقية" />
        <div className="em-hero-copy"><span>منصة النقل الحضري</span><img className="em-hero-logo" src="/assets/masar-logo.png" alt="مسار | MASAR" /><p>رحلات آمنة ومريحة بخدمة عالية الكفاءة لكل وجهة في المنطقة الشرقية.</p><button onClick={enter}>ابدأ رحلتك <BusFront size={18} /></button></div>
      </section>
      <section className="em-intro" id="about"><div><span>عن المنصة</span><h2>خدمة واحدة تربط كل تفاصيل رحلتك</h2><p>مسار منصة موحدة للراكب والسائق وفرق المحطات والتشغيل. يرسل طلب الصعود مباشرة إلى السائق، ويحفظ قرار القبول أو الاعتذار ويعرضه للراكب فورًا.</p></div><div className="em-features"><article><ShieldCheck size={22} /><b>رحلة موثقة</b><span>تفاصيل الخط والدفع وحالة الطلب محفوظة بوضوح.</span></article><article><MapPin size={22} /><b>مطابقة للخريطة</b><span>لا تظهر إلا وجهات الطرفين المعتمدين لكل خط.</span></article><article><Radio size={22} /><b>تشغيل متصل</b><span>لوحات مختلفة، وبيانات طلبات مشتركة.</span></article></div></section>
      <section className="em-network" id="network"><div className="em-section-title"><span>شبكة المنطقة الشرقية</span><h2>اختر خطك بثقة</h2><p>الخريطة الرسمية ومفتاحها المدمج مرجع رحلة مسار. 11 خطًا تشمل الدمام والخبر والقطيف والمطار والمناطق الصناعية.</p></div><div className="em-network-grid"><img src="/assets/eastern-region-official-network-map.png" alt="خريطة خطوط حافلات المنطقة الشرقية مع المفتاح" /></div></section>
    </main>
    <footer><div className="em-partners"><span>شركاء الخدمة</span><img className="partner-municipality" src="/assets/eastern-region-municipality.png" alt="أمانة المنطقة الشرقية" /><img className="partner-bus" src="/assets/eastern-region-bus-partner.png" alt="حافلات المنطقة الشرقية" /></div><p>مسار | منصة تجريبية لخدمات النقل الحضري في المنطقة الشرقية</p></footer>
  </div>;
}

function Login({ login, back }) {
  const [role, setRole] = useState("rider"); const [phone, setPhone] = useState("0551234567"); const [email, setEmail] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const needsOfficialEmail = role === "driver" || role === "station" || role === "ops";
  async function submit(event) { event.preventDefault(); setBusy(true); setError(""); try { login(await api("/auth/login", { method: "POST", body: JSON.stringify({ phone_number: phone, official_email: needsOfficialEmail ? email : null, role }) })); } catch (failure) { setError(failure.message); } finally { setBusy(false); } }
  const roleIcons = { rider: UserRound, driver: BusFront, station: MapPin, ops: LayoutDashboard };
  return <div className="em-login" dir="rtl"><button className="em-back" onClick={back}>العودة للرئيسية</button><div className="em-login-shell"><aside className="em-login-visual"><img src="/assets/eastern-region-bus.jpg" alt="حافلات المنطقة الشرقية" /><div><span>مسار</span><h2>كل رحلة تبدأ بخدمة منظمة.</h2><p>منصة موحدة للراكب والسائق والمحطة ومركز التشغيل.</p></div></aside><main className="em-login-panel"><Brand /><div><span>تسجيل الدخول</span><h1>أهلًا بك في مسار</h1><p>اختر صفتك للوصول إلى واجهة الخدمة المناسبة.</p></div><form onSubmit={submit}><div className="em-role-grid">{Object.entries(roles).map(([key, [title, note]]) => { const Icon = roleIcons[key]; return <button type="button" onClick={() => setRole(key)} className={role === key ? "selected" : ""} key={key}><Icon size={20} /><b>{title}</b><small>{note}</small>{role === key && <Check size={16} className="em-role-check" />}</button>; })}</div><label>رقم الجوال<input value={phone} maxLength="15" inputMode="numeric" placeholder="05XXXXXXXX" onChange={(event) => setPhone(event.target.value.replace(/\D/g, ""))} /></label>{needsOfficialEmail && <label className="em-email-field">البريد الرسمي للمنصة<input type="email" value={email} placeholder="name@masar.sa" onChange={(event) => setEmail(event.target.value)} /><small>يجب أن ينتهي البريد بـ @masar.sa</small></label>}{error && <p className="em-error"><CircleAlert size={16} />{error}</p>}<button className="em-primary" disabled={busy}>{busy ? "جارِ التحقق..." : "دخول آمن"}<LogIn size={17} /></button></form></main></div></div>;
}

function NetworkMap() { return <div className="em-map"><img src="/assets/eastern-region-official-network-map.png" alt="خريطة شبكة المنطقة الشرقية" /><span><Map size={15} />الخريطة الرسمية لشبكة حافلات المنطقة الشرقية</span></div>; }
function Status({ status }) { return <span className={`em-status ${status}`}>{({ pending: "بانتظار مراجعة السائق", accepted: "تم قبول الطلب", declined: "تم الاعتذار", boarded: "تم الصعود" })[status] || status}</span>; }
function BookingList({ bookings, driver, update }) { if (!bookings.length) return <div className="em-empty"><Ticket size={28} /><p>لا توجد طلبات مسجلة حاليًا.</p></div>; return <div className="em-bookings">{bookings.map((booking) => <article key={booking.id}><div className="em-booking-route"><b><i style={{ background: booking.route_color }} />{booking.route_code}</b><span>{booking.origin_name}</span><ArrowLeftRight size={15} /><span>{booking.destination_name}</span></div><div className="em-booking-meta"><span>{booking.rider_name} · {booking.passenger_count} راكب</span><span>{booking.fare_sar} ر.س</span>{booking.assistance ? <span><Accessibility size={14} />مساعدة مطلوبة</span> : null}</div><div className="em-booking-actions"><Status status={booking.status} />{driver && booking.status === "pending" && <><button className="accept" onClick={() => update(booking, "accepted")}>قبول</button><button className="decline" onClick={() => update(booking, "declined")}>اعتذار</button></>}{driver && booking.status === "accepted" && <button className="board" onClick={() => update(booking, "boarded")}>تم الصعود</button>}</div></article>)}</div>; }

function PaymentMark({ method }) { const Icon = method === "apple_pay" ? Smartphone : method === "on_board" ? QrCode : method === "card" ? CreditCard : WalletCards; return <span className={`em-payment-icon ${method}`}><Icon size={18} />{method === "mada" && <b>mada</b>}{method === "apple_pay" && <b>Pay</b>}</span>; }

function Rider({ network, user, bookings, refresh }) {
  const [routeCode, setRouteCode] = useState("A2"), [reverse, setReverse] = useState(false), [count, setCount] = useState(1), [payment, setPayment] = useState("mada"), [assistance, setAssistance] = useState(false), [message, setMessage] = useState(""), [details, setDetails] = useState({ number: "", name: "", expiry: "", cvv: "", confirmed: false }); const [busy, setBusy] = useState(false);
  const route = network.routes.find((item) => item.code === routeCode) || network.routes[0]; const isLoop = route.type === "loop"; const origin = reverse && !isLoop ? route.destination : route.origin; const destination = reverse && !isLoop ? route.origin : route.destination;
  useEffect(() => setReverse(false), [routeCode]);
  function choosePayment(value) { setPayment(value); setDetails({ number: "", name: "", expiry: "", cvv: "", confirmed: value === "on_board" }); }
  function updateDetail(key, value) { setDetails((current) => ({ ...current, [key]: value })); }
  function paymentReady() { if (payment === "on_board") return true; if (payment === "apple_pay") return details.confirmed; return details.number.replace(/\s/g, "").length >= 12 && details.name.trim().length >= 3 && details.expiry.length === 5 && details.cvv.length >= 3; }
  async function submit(event) { event.preventDefault(); setMessage(""); if (!paymentReady()) { setMessage(payment === "apple_pay" ? "أكد الدفع عبر Apple Pay قبل إتمام الحجز." : "أكمل بيانات الدفع المطلوبة قبل إتمام الحجز."); return; } setBusy(true); try { const booking = await api("/bookings", { method: "POST", body: JSON.stringify({ rider_id: user.user_id, rider_name: user.name, route_code: route.code, origin_name: origin, destination_name: destination, passenger_count: count, assistance, payment_method: payment }) }); setMessage(`تم تسجيل طلبك ${booking.id}. سيصل الرد من السائق خلال وقت قصير.`); refresh(); } catch (failure) { setMessage(failure.message); } finally { setBusy(false); } }
  const paymentSteps = payment === "on_board" ? <div className="em-payment-procedure"><QrCode size={23} /><div><b>الدفع عند الصعود</b><p>سيظهر رمز تذكرتك للسائق بعد قبول الطلب، وتدفع {((count * network.fare_sar).toFixed(2))} ر.س عند الصعود.</p></div></div> : payment === "apple_pay" ? <div className="em-payment-procedure"><Smartphone size={23} /><div><b>تأكيد Apple Pay</b><p>ستظهر نافذة Apple Pay على جهازك لتأكيد المبلغ. لا تحفظ مسار أي بيانات دفع.</p><button type="button" className={details.confirmed ? "confirmed" : ""} onClick={() => updateDetail("confirmed", true)}>{details.confirmed ? "تم تأكيد Apple Pay" : "تأكيد الدفع عبر Apple Pay"}</button></div></div> : <div className="em-payment-procedure em-card-procedure"><div className="em-procedure-head"><PaymentMark method={payment} /><div><b>{payment === "mada" ? "الدفع عبر مدى" : "دفع بالبطاقة"}</b><p>بيانات تجريبية محمية، ولا يتم إرسالها إلى بنك أو بوابة خارجية.</p></div><LockKeyhole size={16} /></div><div className="em-card-fields"><input aria-label="رقم البطاقة" inputMode="numeric" placeholder="رقم البطاقة" value={details.number} onChange={(event) => updateDetail("number", event.target.value.replace(/[^\d ]/g, "").slice(0, 19))} /><input aria-label="اسم حامل البطاقة" placeholder="اسم حامل البطاقة" value={details.name} onChange={(event) => updateDetail("name", event.target.value)} /><input aria-label="تاريخ الانتهاء" inputMode="numeric" placeholder="MM/YY" value={details.expiry} onChange={(event) => updateDetail("expiry", event.target.value.replace(/[^\d/]/g, "").slice(0, 5))} /><input aria-label="رمز الأمان" inputMode="numeric" placeholder="CVV" value={details.cvv} onChange={(event) => updateDetail("cvv", event.target.value.replace(/\D/g, "").slice(0, 4))} /></div></div>;
  return <><div className="em-page-title"><span>خدمة الراكب</span><h1>احجز رحلة على خطوط المنطقة الشرقية</h1><p>تظهر المحطات النهائية فقط بحسب المفتاح الرسمي للخريطة، لضمان أن تفاصيل رحلتك صحيحة.</p></div><div className="em-rider-grid"><form className="em-book-form" onSubmit={submit}><label>اختر الخط<select value={routeCode} onChange={(event) => setRouteCode(event.target.value)}>{network.routes.map((item) => <option key={item.code} value={item.code}>الخط {item.code} | {item.origin} - {item.destination}{item.type === "loop" ? " (دائري)" : ""}</option>)}</select></label><div className="em-route-summary"><span><i style={{ background: route.color }} />الخط {route.code}</span><b>{isLoop ? "خدمة دائرية" : "ذهاب وعودة"}</b></div><div className="em-stops"><label>الانطلاق<input readOnly value={origin} /></label><button type="button" disabled={isLoop} onClick={() => setReverse(!reverse)} aria-label="عكس اتجاه الرحلة"><ArrowLeftRight size={18} /></button><label>الوصول<input readOnly value={destination} /></label></div>{isLoop && <p className="em-note">B2 خدمة دائرية في الخبر الشمالية 1 كما هو موضح في مفتاح الخريطة.</p>}<div className="em-form-row"><label>عدد الركاب<input type="number" min="1" max="8" value={count} onChange={(event) => setCount(Math.max(1, Math.min(8, Number(event.target.value))))} /></label><div className="em-fare"><small>إجمالي الرحلة</small><b>{(count * network.fare_sar).toFixed(2)} ر.س</b><span>3.45 ر.س لكل راكب</span></div></div><fieldset><legend>طريقة الدفع</legend><div className="em-payments">{[["mada", "مدى"], ["apple_pay", "Apple Pay"], ["card", "بطاقة"], ["on_board", "عند الصعود"]].map(([value, label]) => <button type="button" className={payment === value ? "picked" : ""} onClick={() => choosePayment(value)} key={value}><PaymentMark method={value} /><span>{label}</span></button>)}</div></fieldset>{paymentSteps}<label className="em-check"><input type="checkbox" checked={assistance} onChange={(event) => setAssistance(event.target.checked)} /><Accessibility size={17} />أحتاج مساعدة أو أولوية عند الصعود</label><button className="em-primary" disabled={busy}>{busy ? "جارِ إرسال الطلب..." : payment === "on_board" ? "تأكيد الحجز والدفع عند الصعود" : "تأكيد الدفع والحجز"}<Send size={17} /></button>{message && <p className={message.startsWith("تم") ? "em-success" : "em-error"}>{message}</p>}</form><NetworkMap /></div><section className="em-section"><div className="em-section-head"><div><span>طلباتي</span><h2>متابعة الرحلات</h2></div></div><BookingList bookings={bookings} /></section></>;
}

function OperationsCenter({ network, bookings, language = "ar" }) {
  const [tab, setTab] = useState("overview"); const [dss, setDss] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [tableName, setTableName] = useState("routes"); const [tablePreview, setTablePreview] = useState(null); const [tableLoading, setTableLoading] = useState(false); const [scenarioId, setScenarioId] = useState(""); const [strength, setStrength] = useState(0.55); const [simulation, setSimulation] = useState(null); const [simulationLoading, setSimulationLoading] = useState(false); const [generateMessage, setGenerateMessage] = useState("");
  const loadDss = async () => { setLoading(true); setError(""); try { const [kpis, quality, scenarios, recommendation, model] = await Promise.all([api("/kpis"), api("/data-quality"), api("/scenarios"), api("/recommendation"), api("/data-model")]); setDss({ kpis, quality, scenarios, recommendation, model }); } catch (failure) { setError(failure.message); } finally { setLoading(false); } };
  const loadTable = async (name) => { setTableLoading(true); try { setTablePreview(await api(`/tables/${name}?limit=8`)); } catch (failure) { setError(failure.message); } finally { setTableLoading(false); } };
  const generateDataset = async () => { setGenerateMessage(""); try { const result = await api("/generate", { method: "POST" }); setGenerateMessage(result.message); await loadDss(); await loadTable(tableName); } catch (failure) { setError(failure.message); } };
  const chooseScenario = (scenario) => { setScenarioId(scenario.scenario_id); setStrength(scenario.intervention_strength); setSimulation(null); };
  useEffect(() => { loadDss(); loadTable("routes"); }, []);
  const active = bookings.filter((item) => ["pending", "accepted"].includes(item.status)).length;
  if (loading) return <div className="em-ops-loading"><Radio className="em-spin" size={25} />جارِ تحميل بيانات مركز التشغيل...</div>;
  if (error) return <div className="em-ops-loading"><CircleAlert size={25} />{error}<button onClick={loadDss}>إعادة المحاولة</button></div>;
  const summary = dss.kpis.kpis; const causes = dss.kpis.cause_summary; const maxCause = Math.max(...causes.map((item) => item.total_added_delay_sec), 1); const selectedScenario = dss.scenarios.find((item) => item.scenario_id === scenarioId) || dss.scenarios[0];
  const ar = { "North Station": "المحطة الشمالية", "Market Street": "شارع السوق", "Central Hospital": "المستشفى المركزي", "University Gate": "بوابة الجامعة", "Civic Center": "المركز المدني", "Organized Boarding": "تنظيم صعود الركاب", "Schedule Adjustment": "تعديل الجدول", "Additional Bus": "إضافة حافلة", "Ticket Machine": "جهاز تذاكر", "Staff organize boarding at the most delayed stop.": "تنظيم صعود الركاب في المحطة الأعلى تأخيرًا.", "Adjust headway before the busiest segment.": "تعديل الفاصل الزمني قبل المقطع الأعلى ازدحامًا.", "Identity and completeness": "الهوية والاكتمال", "Foreign keys": "العلاقات المرجعية", "Time and numeric values": "الوقت والقيم الرقمية", "Passenger capacity": "سعة الركاب", "Stop sequence": "تسلسل المحطات", "All expected tables exist.": "جميع الجداول المتوقعة موجودة.", "Every stop event references an existing trip.": "كل حدث توقف مرتبط برحلة موجودة.", "Every stop event references an existing stop.": "كل حدث توقف مرتبط بمحطة موجودة.", "Time, load, and delay values are not negative.": "قيم الوقت والحمولة والتأخير غير سالبة.", "Passenger load does not exceed bus capacity.": "حمولة الركاب لا تتجاوز سعة الحافلة.", "Stop sequence increases within each trip.": "تسلسل المحطات متزايد داخل كل رحلة.", "Low": "منخفضة", "Medium": "متوسطة", "High": "مرتفعة" }; const local = (value) => language === "ar" ? (ar[value] || value) : value;
  const switchTable = (name) => { setTableName(name); loadTable(name); };
  const runSimulation = async () => { setSimulationLoading(true); try { setSimulation(await api("/scenarios/simulate", { method: "POST", body: JSON.stringify({ scenario_id: selectedScenario.scenario_id, saving_factor: strength }) })); } catch (failure) { setError(failure.message); } finally { setSimulationLoading(false); } };
  return <section className="em-operations">
    <div className="em-page-title"><span>مركز التشغيل والتحليل</span><h1>لوحة التحكم الذكية</h1><p>خدمات التشغيل الحية مع كامل أدوات دعم القرار الأصلية للمشروع.</p></div>
    <div className="em-ops-tabs">{[["overview", LayoutDashboard, "نظرة عامة"], ["data", Database, "البيانات والجودة"], ["scenarios", FlaskConical, "مختبر السيناريو"], ["recommendation", Lightbulb, "التوصية"]].map(([key, Icon, label]) => <button className={tab === key ? "active" : ""} onClick={() => setTab(key)} key={key}><Icon size={17} />{label}</button>)}<button className="em-ops-refresh" onClick={loadDss} aria-label="تحديث بيانات التحليل"><RefreshCw size={17} /></button></div>
    {tab === "overview" && <><div className="em-kpis em-dss-kpis"><article><BarChart3 size={20} /><div><small>الالتزام بالموعد</small><b>{Math.round(summary.on_time_rate * 100)}%</b><span>{summary.trips_analyzed} رحلة محللة</span></div></article><article><BusFront size={20} /><div><small>متوسط التأخير</small><b>{Math.round(summary.avg_final_delay_sec / 60)} د</b><span>لكل رحلة في بيانات التدريب</span></div></article><article><MapPin size={20} /><div><small>أعلى محطة تأخيرًا</small><b>{local(summary.worst_stop)}</b><span>من تحليل أحداث التوقف</span></div></article><article><Users size={20} /><div><small>طلبات حية</small><b>{active}</b><span>{bookings.length} طلب محفوظ في مسار</span></div></article></div><div className="em-ops-grid"><section className="em-section"><div className="em-section-head"><div><span>الخريطة التشغيلية</span><h2>شبكة المنطقة الشرقية</h2></div></div><NetworkMap /></section><section className="em-section"><div className="em-section-head"><div><span>مصادر التأخير</span><h2>تحليل مجموعة البيانات</h2></div></div><div className="em-cause-bars">{causes.map((item) => <div key={item.delay_cause}><span>{{ boarding: "صعود الركاب", traffic: "الازدحام المروري", schedule_gap: "فجوة الجدول" }[item.delay_cause] || item.delay_cause}</span><i><b style={{ width: `${Math.round(item.total_added_delay_sec / maxCause * 100)}%` }} /></i><em>{Math.round(item.total_added_delay_sec / 60)} د</em></div>)}</div><p className="em-dataset-note"><Database size={15} />بيانات B12 التدريبية مستقلة عن خريطة المنطقة الشرقية الرسمية.</p></section></div><section className="em-section"><div className="em-section-head"><div><span>أداء المحطات</span><h2>أعلى نقاط المراقبة</h2></div></div><div className="em-stop-grid">{dss.kpis.stop_summary.slice(0, 5).map((stop) => <article key={stop.stop_id}><b>{local(stop.stop_name)}</b><span>تأخير مضاف {Math.round(stop.avg_added_delay_sec)} ث</span><small>حمولة متوسطة {Math.round(stop.avg_passenger_load)} راكب</small></article>)}</div></section></>}
    {tab === "data" && <><div className="em-ops-grid"><section className="em-section"><div className="em-section-head"><div><span>بوابة جودة البيانات</span><h2>{dss.quality.passed ? "البيانات صالحة للتحليل" : "تحتاج البيانات إلى مراجعة"}</h2></div><span className={dss.quality.passed ? "em-quality-pass" : "em-quality-fail"}>{Math.round(dss.quality.quality_score * 100)}%</span></div><div className="em-quality-list">{dss.quality.checks.map((check) => <div key={check.id}><CheckCircle2 size={17} /><div><b>{check.category}</b><span>{check.message}</span></div><em>{check.severity}</em></div>)}</div></section><section className="em-section"><div className="em-section-head"><div><span>نموذج البيانات</span><h2>الجداول والعلاقات</h2></div><button className="em-data-action" onClick={generateDataset}><RefreshCw size={15} />توليد البيانات</button></div><div className="em-table-list">{dss.model.tables.map((table) => <button className={tableName === table.name ? "active" : ""} onClick={() => switchTable(table.name)} key={table.name}><Database size={18} /><div><b>{table.name}</b><span>{table.row_count} صف · {table.columns.length} حقل</span><small>{table.purpose}</small></div></button>)}</div>{generateMessage && <p className="em-success">{generateMessage}</p>}<p className="em-dataset-note"><Database size={15} />العلاقة: {dss.model.relationship}</p></section></div><section className="em-section em-erd"><div className="em-section-head"><div><span>مخطط قاعدة البيانات</span><h2>العلاقات بين الجداول</h2></div></div><div className="em-erd-flow"><article><b>routes</b><span>route_id</span></article><i>1 : N</i><article><b>trips</b><span>trip_id · route_id</span></article><i>1 : N</i><article><b>stop_events</b><span>trip_id · stop_id</span></article><i>N : 1</i><article><b>stops</b><span>stop_id · route_id</span></article></div></section><section className="em-section em-data-preview"><div className="em-section-head"><div><span>مستعرض البيانات</span><h2>{tablePreview?.table || tableName}</h2></div>{tableLoading && <Radio className="em-spin" size={17} />}</div>{tablePreview && <div className="em-scroll-table"><table><thead><tr>{tablePreview.columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{tablePreview.rows.map((row, index) => <tr key={index}>{tablePreview.columns.map((column) => <td key={column}>{String(row[column] ?? "-")}</td>)}</tr>)}</tbody></table></div>}</section></>}
    {tab === "scenarios" && <section className="em-section"><div className="em-section-head"><div><span>مختبر السيناريو</span><h2>اختبر التدخل قبل تطبيقه</h2><p>اختر السيناريو، عدّل قوة التدخل، ثم شغّل المحاكاة على الخادم.</p></div></div><div className="em-scenario-grid">{dss.scenarios.map((scenario) => <button type="button" onClick={() => chooseScenario(scenario)} className={scenario.scenario_id === selectedScenario.scenario_id ? "best" : ""} key={scenario.scenario_id}><div><span>{scenario.scenario_id}</span><b>{scenario.name}</b><small>{scenario.description}</small></div><dl><div><dt>التحسن المتوقع</dt><dd>{scenario.improvement_sec.toFixed(1)} ث</dd></div><div><dt>الثقة</dt><dd>{Math.round(scenario.confidence * 100)}%</dd></div><div><dt>درجة الإجراء</dt><dd>{scenario.action_score.toFixed(2)}</dd></div></dl><p>المحطة: {scenario.target_stop_name} · التكلفة: {scenario.cost_level}</p></button>)}</div><div className="em-simulation-control"><div><b>قوة التدخل: {Math.round(strength * 100)}%</b><input type="range" min="0.05" max="0.95" step="0.05" value={strength} onChange={(event) => setStrength(Number(event.target.value))} /><small>كلما زادت القوة، ارتفع خفض وقت الانتظار المفترض في المحطة المستهدفة.</small></div><button className="em-primary" type="button" disabled={simulationLoading} onClick={runSimulation}>{simulationLoading ? "جارِ تشغيل المحاكاة..." : "تشغيل المحاكاة"}<FlaskConical size={17} /></button></div><div className="em-scenario-detail"><div><b>افتراضات {selectedScenario.name}</b>{(simulation?.assumptions || selectedScenario.assumptions).map((item) => <span key={item}>{item}</span>)}</div><div><b>صفوف متأثرة</b><small>{(simulation?.affected_rows || selectedScenario.affected_rows).slice(0, 4).map((row) => `${row.trip_id}: ${row.improvement_sec.toFixed(1)} ث`).join(" · ")}</small></div></div>{simulation && <div className="em-simulation-result"><article><small>التأخير بعد المحاكاة</small><b>{Math.round(simulation.scenario_avg_delay_sec / 60)} د</b></article><article><small>التحسن المحسوب</small><b>{simulation.improvement_sec.toFixed(1)} ث</b></article><article><small>الثقة / درجة الإجراء</small><b>{Math.round(simulation.confidence * 100)}% / {simulation.action_score.toFixed(2)}</b></article></div>}</section>}
    {tab === "recommendation" && <section className="em-recommendation"><div className="em-recommendation-head"><Lightbulb size={28} /><div><span>توصية قابلة للتفسير</span><h2>{dss.recommendation.recommended_action}</h2><p>{dss.recommendation.evidence.scenario_description}</p></div><b>{Math.round(dss.recommendation.confidence * 100)}% ثقة</b></div><div className="em-recommendation-grid"><article><small>المحطة المستهدفة</small><b>{dss.recommendation.evidence.worst_stop}</b></article><article><small>التحسن المتوقع</small><b>{dss.recommendation.expected_improvement_sec.toFixed(1)} ثانية</b></article><article><small>درجة الإجراء</small><b>{dss.recommendation.action_score.toFixed(2)}</b></article></div><div className="em-recommendation-next"><b>الخطوة التالية</b><p>{dss.recommendation.next_step}</p><small>{dss.recommendation.audit_note}</small></div><div className="em-limitations"><b>حدود التحليل</b>{dss.recommendation.limitations.map((item) => <span key={item}>{item}</span>)}</div></section>}
  </section>;
}

function Staff({ network, user, bookings, refresh, language }) {
  if (user.role === "ops") return <OperationsCenter network={network} bookings={bookings} language={language} />;
  const driver = user.role === "driver"; const active = bookings.filter((item) => ["pending", "accepted"].includes(item.status)).length;
  async function update(booking, status) { try { await api(`/bookings/${booking.id}`, { method: "PATCH", body: JSON.stringify({ status, actor_role: "driver", driver_note: "" }) }); refresh(); } catch (failure) { window.alert(failure.message); } }
  return <><div className="em-page-title"><span>{driver ? "واجهة السائق" : user.role === "ops" ? "مركز التشغيل" : "إدارة المحطة"}</span><h1>{driver ? "طلبات الصعود للرحلات" : "متابعة شبكة حافلات المنطقة الشرقية"}</h1><p>بيانات موحدة للطلبات، مع خريطة الشبكة الرسمية ومؤشرات خدمات مباشرة.</p></div><div className="em-kpis"><article><BusFront size={20} /><div><small>الخطوط المعتمدة</small><b>{network.routes.length}</b><span>وفق مفتاح الخريطة</span></div></article><article><Users size={20} /><div><small>طلبات نشطة</small><b>{active}</b><span>بانتظار السائق أو مقبولة</span></div></article><article><CreditCard size={20} /><div><small>إيراد الطلبات</small><b>{bookings.reduce((total, item) => total + Number(item.fare_sar), 0).toFixed(2)} ر.س</b><span>بسعر موحد 3.45 ر.س</span></div></article><article><LayoutDashboard size={20} /><div><small>حالة الشبكة</small><b>متاحة</b><span>11 خدمة معرفة</span></div></article></div><div className="em-staff-grid"><NetworkMap /><section className="em-section"><div className="em-section-head"><div><span>الطلبات المشتركة</span><h2>{driver ? "راجع طلبات الركاب" : "آخر طلبات الصعود"}</h2></div></div><BookingList bookings={bookings} driver={driver} update={update} /></section></div></>;
}

function Workspace({ user, network, logout }) {
  const [bookings, setBookings] = useState([]); const [error, setError] = useState(""); const [language, setLanguage] = useState(() => sessionStorage.getItem("masar-language") || "ar");
  const refresh = async () => { try { const path = user.role === "rider" ? `/bookings?rider_id=${user.user_id}` : "/bookings"; setBookings((await api(path)).bookings); } catch (failure) { setError(failure.message); } };
  useEffect(() => { refresh(); const timer = window.setInterval(refresh, 5000); return () => window.clearInterval(timer); }, [user.user_id, user.role]);
  const changeLanguage = () => { const next = language === "ar" ? "en" : "ar"; sessionStorage.setItem("masar-language", next); setLanguage(next); };
  const roleName = language === "en" ? ({ rider: "Rider", driver: "Driver", station: "Station staff", ops: "Operations" })[user.role] : roles[user.role][0];
  return <div className={`em-app language-${language}`} dir={language === "en" ? "ltr" : "rtl"}><header><Brand /><div className="em-account"><button className="em-language-switch" onClick={changeLanguage} aria-label="Change language">{language === "ar" ? "English" : "العربية"}</button><span>{user.name}</span><small>{roleName}</small><button onClick={logout} aria-label={language === "en" ? "Sign out" : "تسجيل الخروج"}><LogOut size={17} /></button></div></header><main>{error && <p className="em-error"><CircleAlert size={16} />{error}</p>}{user.role === "rider" ? <Rider network={network} user={user} bookings={bookings} refresh={refresh} /> : <Staff network={network} user={user} bookings={bookings} refresh={refresh} language={language} />}</main></div>;
}

export default function EasternMasar() {
  const [mode, setMode] = useState(() => sessionStorage.getItem("masar-user") ? "app" : "home"); const [user, setUser] = useState(() => { try { return JSON.parse(sessionStorage.getItem("masar-user")); } catch { return null; } }); const [network, setNetwork] = useState(null); const [error, setError] = useState("");
  useEffect(() => { api("/network").then(setNetwork).catch((failure) => setError(failure.message)); }, []);
  function login(profile) { sessionStorage.setItem("masar-user", JSON.stringify(profile)); setUser(profile); setMode("app"); }
  function logout() { sessionStorage.removeItem("masar-user"); setUser(null); setMode("home"); }
  if (error) return <div className="em-loading" dir="rtl"><CircleAlert size={28} /><h1>تعذر الاتصال بخدمة مسار</h1><p>{error}</p></div>;
  if (!network) return <div className="em-loading" dir="rtl"><Radio className="em-spin" size={28} /><p>جارِ تحميل شبكة المنطقة الشرقية...</p></div>;
  if (mode === "login") return <Login login={login} back={() => setMode("home")} />;
  if (mode === "app" && user) return <Workspace user={user} network={network} logout={logout} />;
  return <PublicHome enter={() => setMode("login")} />;
}
