import { useEffect, useMemo, useState } from "react";
import { Accessibility, ArrowLeft, Bell, BusFront, CalendarDays, CheckCircle2, ChevronLeft, CircleAlert, Clock3, CreditCard, LayoutDashboard, MapPin, Radio, Route, Send, ShieldCheck, Ticket, Users, UserRound } from "lucide-react";

const STORAGE = "masar-platform-requests-v1";
const stopNames = { "North Station": "المحطة الشمالية", "Market Street": "شارع السوق", "Central Hospital": "المستشفى المركزي", "University Gate": "بوابة الجامعة", "Civic Center": "المركز المدني" };
const delayText = { schedule_gap: "فجوة بالجدول", traffic: "ازدحام مروري", boarding: "صعود مرتفع" };
const csv = (text) => { const [header, ...rows] = text.trim().split(/\r?\n/); const keys = header.split(","); return rows.filter(Boolean).map((row) => Object.fromEntries(keys.map((key, i) => [key, row.split(",")[i] ?? ""]))); };
const name = (stop) => stopNames[stop?.stop_name] || stop?.stop_name || "-";
const time = (date, add) => { const value = new Date(date); value.setMinutes(value.getMinutes() + Number(add)); return value.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" }); };

const profiles = {
  rider: { label: "بوابة الراكب", person: "أهلًا، سارة", role: "راكب", icon: Ticket },
  driver: { label: "بوابة السائق", person: "خالد العتيبي", role: "سائق · B12", icon: BusFront },
  station: { label: "بوابة المحطة", person: "محطة السوق", role: "موظف محطة", icon: MapPin },
  ops: { label: "بوابة التشغيل", person: "مركز التحكم", role: "مشرف تشغيل", icon: LayoutDashboard },
};

function Metric({ icon: Icon, label, value, note, tone = "" }) { return <article className={`platform-metric ${tone}`}><span className="metric-icon"><Icon size={18} /></span><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></article>; }
function Section({ title, action, children }) { return <section className="platform-section"><div className="section-head"><h2>{title}</h2>{action}</div>{children}</section>; }
function Field({ label, children }) { return <label className="platform-field"><span>{label}</span>{children}</label>; }

export default function MasarPlatform() {
  const [data, setData] = useState();
  const [error, setError] = useState("");
  const [profile, setProfile] = useState("rider");
  const [requests, setRequests] = useState(() => { try { return JSON.parse(localStorage.getItem(STORAGE) || "[]"); } catch { return []; } });
  const [requestForm, setRequestForm] = useState({ origin: "2", destination: "5", passengers: "1", assistance: false });
  const [message, setMessage] = useState("");

  useEffect(() => { Promise.all(["routes", "stops", "trips", "stop_events"].map(async (file) => { const response = await fetch(`/data/${file}.csv`); if (!response.ok) throw new Error("تعذر تحميل بيانات التشغيل."); return csv(await response.text()); })).then(([routes, stops, trips, events]) => { stops.sort((a, b) => +a.sequence - +b.sequence); trips.sort((a, b) => new Date(a.departure_time) - new Date(b.departure_time)); setData({ route: routes[0], stops, trips, events }); }).catch((loadError) => setError(loadError.message)); }, []);
  useEffect(() => localStorage.setItem(STORAGE, JSON.stringify(requests)), [requests]);

  const model = useMemo(() => {
    if (!data) return null;
    const trip = data.trips[Math.floor(data.trips.length / 2)];
    const events = data.events.filter((event) => event.trip_id === trip.trip_id).sort((a, b) => +a.sequence - +b.sequence);
    const average = (items, key) => items.reduce((sum, item) => sum + +item[key], 0) / Math.max(items.length, 1);
    const onTime = Math.round(data.trips.filter((item) => +item.final_delay_sec <= 180).length / data.trips.length * 100);
    const busiest = [...data.stops].sort((a, b) => average(data.events.filter((event) => event.stop_id === b.stop_id), "passengers_boarding") - average(data.events.filter((event) => event.stop_id === a.stop_id), "passengers_boarding"))[0];
    return { ...data, trip, events, onTime, busiest, avgDelay: Math.round(average(data.trips, "final_delay_sec") / 60) };
  }, [data]);

  if (error) return <div className="platform-state"><CircleAlert size={32} /><h1>تعذر تحميل منصة مسار</h1><p>{error}</p></div>;
  if (!model) return <div className="platform-state"><Radio className="spin" size={30} /><p>يتم تجهيز منصة مسار...</p></div>;

  const event = model.events[1];
  const submit = () => {
    const origin = +requestForm.origin, destination = +requestForm.destination, passengers = +requestForm.passengers;
    if (!Number.isInteger(passengers) || passengers < 1 || passengers > 8) return setMessage("يرجى إدخال عدد ركاب بين 1 و8.");
    if (destination <= origin) return setMessage("اختر وجهة بعد محطة الانطلاق على خط B12.");
    const originEvent = model.events[origin - 1];
    const eta = Math.max(1, Math.round(+originEvent.actual_arrival_min - +event.actual_arrival_min));
    const record = { id: `MSR-${Date.now().toString().slice(-6)}`, origin, destination, passengers, assistance: requestForm.assistance, eta, createdAt: new Date().toISOString(), status: "بانتظار الباص" };
    setRequests((current) => [record, ...current]);
    setMessage(`تم تسجيل طلبك. وصول الباص إلى ${name(model.stops[origin - 1])} خلال ${eta} دقائق.`);
  };
  const nav = [["rider", Ticket, "الراكب"], ["driver", BusFront, "السائق"], ["station", MapPin, "المحطة"], ["ops", LayoutDashboard, "التشغيل"]];
  const ProfileIcon = profiles[profile].icon;

  return <div className="saudi-platform" dir="rtl"><aside className="entity-sidebar"><div className="entity-brand"><span className="entity-mark"><Route size={25} /></span><div><strong>مسار</strong><small>MASAR</small></div></div><div className="entity-caption">منصة النقل الحضري</div><nav>{nav.map(([key, Icon, label]) => <button className={profile === key ? "selected" : ""} onClick={() => { setProfile(key); setMessage(""); }} key={key}><Icon size={18} />{label}</button>)}</nav><div className="entity-support"><ShieldCheck size={17} /><div><b>الدعم والمساعدة</b><span>24/7 · 19933</span></div></div></aside><div className="platform-body"><header className="entity-header"><div className="crumb"><span>مسار</span><ChevronLeft size={14} /><b>{profiles[profile].label}</b></div><div className="profile-menu"><Bell size={18} /><span className="avatar">{profiles[profile].person.slice(0, 1)}</span><div><b>{profiles[profile].person}</b><small>{profiles[profile].role}</small></div></div></header><main className="platform-content"><div className="welcome"><div><span className="entity-kicker">الهيئة السعودية للنقل</span><h1>{profile === "rider" ? "رحلتك، بكل سهولة" : profiles[profile].label}</h1><p>{profile === "rider" ? "خطط رحلتك واطلب الصعود من محطتك، مع وصول محسوب من بيانات التشغيل." : "بيانات موحدة ومباشرة لخط B12، مصممة لدعم القرار في الوقت المناسب."}</p></div><div className="network-status"><Radio size={16} /><span>الخدمة تعمل بشكل طبيعي</span><b>B12</b></div></div>{profile === "rider" && <Rider model={model} form={requestForm} setForm={setRequestForm} submit={submit} message={message} requests={requests} />}{profile === "driver" && <Driver model={model} requests={requests} />}{profile === "station" && <Station model={model} requests={requests} />}{profile === "ops" && <Operations model={model} requests={requests} />}</main></div></div>;
}

function Rider({ model, form, setForm, submit, message, requests }) { const update = (key, value) => setForm((current) => ({ ...current, [key]: value })); const upcoming = requests[0]; return <><div className="platform-metrics"><Metric icon={Clock3} label="أقرب رحلة" value={time(model.trip.departure_time, model.events[1].actual_arrival_min)} note="من شارع السوق" tone="green" /><Metric icon={Route} label="حالة الخط" value="منتظم" note={`متوسط التأخير ${model.avgDelay} دقائق`} /><Metric icon={Ticket} label="طلباتي" value={requests.length} note="طلبات محفوظة في المنصة" /></div><div className="platform-grid rider-grid"><Section title="طلب صعود جديد"><div className="request-card"><div className="form-row"><Field label="محطة الانطلاق"><select value={form.origin} onChange={(e) => update("origin", e.target.value)}>{model.stops.map((stop) => <option value={stop.sequence} key={stop.stop_id}>{name(stop)}</option>)}</select></Field><Field label="الوجهة"><select value={form.destination} onChange={(e) => update("destination", e.target.value)}>{model.stops.map((stop) => <option value={stop.sequence} key={stop.stop_id}>{name(stop)}</option>)}</select></Field></div><div className="form-row"><Field label="عدد الركاب"><input type="number" min="1" max="8" value={form.passengers} onChange={(e) => update("passengers", e.target.value)} /></Field><label className="assist-toggle"><input type="checkbox" checked={form.assistance} onChange={(e) => update("assistance", e.target.checked)} /><Accessibility size={17} />أحتاج مساعدة عند الصعود</label></div><button className="saudi-primary" onClick={submit}><Send size={17} />تأكيد طلب الصعود</button>{message && <p className={message.startsWith("تم") ? "form-feedback success" : "form-feedback error"}>{message}</p>}</div></Section><Section title="رحلتي القادمة" action={<button className="text-link">عرض التذكرة <ArrowLeft size={15} /></button>}><div className="journey-card"><div className="route-points"><span /><i /><span /></div><div><b>{upcoming ? name(model.stops[upcoming.origin - 1]) : "شارع السوق"}</b><small>{upcoming ? `وصول الباص خلال ${upcoming.eta} دقائق` : "الوصول المتوقع 11:36"}</small></div><div><b>{upcoming ? name(model.stops[upcoming.destination - 1]) : "المركز المدني"}</b><small>{upcoming ? `${upcoming.passengers} راكب` : "الوصول المتوقع 11:56"}</small></div><span className="journey-status">{upcoming?.status || "مجدولة"}</span></div></Section></div></>; }
function Driver({ model, requests }) { const current = model.events[1], load = Math.round(+current.passenger_load / +current.bus_capacity * 100), next = model.stops.slice(2); return <><div className="platform-metrics"><Metric icon={Users} label="حمولة الباص" value={`${current.passenger_load} / ${current.bus_capacity}`} note={`${load}% من السعة`} tone="green" /><Metric icon={Bell} label="طلبات الصعود" value={requests.length} note="طلبات تحتاج متابعة" /><Metric icon={Clock3} label="التأخير التراكمي" value={`${Math.round(+current.cumulative_delay_sec / 60)} د`} note={delayText[current.delay_cause]} /></div><div className="platform-grid driver-platform"><Section title="خطة الرحلة"><div className="driver-route">{next.map((stop) => { const item = model.events[+stop.sequence - 1], count = requests.filter((request) => request.origin === +stop.sequence).reduce((sum, request) => sum + request.passengers, 0); return <div key={stop.stop_id}><span className={item.added_delay_sec > 60 ? "risk" : ""} /><div><b>{name(stop)}</b><small>{count ? `${count} راكب بانتظار طلب الصعود` : `متوقع صعود ${item.passengers_boarding} راكب`}</small></div><em>{time(model.trip.departure_time, item.actual_arrival_min)}</em></div>; })}</div></Section><Section title="تنبيه الرحلة"><div className="attention-card"><CircleAlert size={22} /><div><b>{load > 80 ? "حمولة مرتفعة في الباص" : "حالة الرحلة مستقرة"}</b><p>{load > 80 ? "تابع حركة الصعود عند المحطة التالية وتحقق من طلبات المساعدة." : "لا توجد إجراءات تشغيلية عاجلة في الوقت الحالي."}</p></div></div></Section></div></>; }
function Station({ model, requests }) { const station = model.stops[1], nextTrips = model.trips.slice(18, 21); return <><div className="platform-metrics"><Metric icon={MapPin} label="المحطة الحالية" value={name(station)} note="خط B12" tone="green" /><Metric icon={Clock3} label="وقت الوصول التالي" value={time(model.trip.departure_time, model.events[1].actual_arrival_min)} note={delayText[model.events[1].delay_cause]} /><Metric icon={Users} label="طلبات المحطة" value={requests.filter((item) => item.origin === 2).length} note="طلبات صعود نشطة" /></div><div className="platform-grid station-grid"><Section title="لوحة المغادرات"><div className="departures">{nextTrips.map((trip) => { const event = model.events[1]; return <div key={trip.trip_id}><b>{time(trip.departure_time, event.actual_arrival_min)}</b><span><strong>المركز المدني</strong><small>{trip.trip_id} · B12</small></span><em>{delayText[event.delay_cause]}</em></div>; })}</div></Section><Section title="خدمة المسافرين"><div className="station-service"><Accessibility size={23} /><div><b>طلبات المساعدة</b><p>{requests.filter((item) => item.assistance).length ? "يوجد طلب مساعدة مسجل للسائق." : "لا توجد طلبات مساعدة تحتاج تدخلًا الآن."}</p></div><button className="outline-action">تحديث اللوحة</button></div></Section></div></>; }
function Operations({ model, requests }) { const all = model.events, totals = ["traffic", "boarding", "schedule_gap"].map((cause) => ({ cause, amount: all.filter((item) => item.delay_cause === cause).reduce((sum, item) => sum + +item.added_delay_sec, 0) })); const total = totals.reduce((sum, item) => sum + item.amount, 0); return <><div className="platform-metrics"><Metric icon={CheckCircle2} label="الالتزام بالمواعيد" value={`${model.onTime}%`} note="التأخير 3 دقائق أو أقل" tone="green" /><Metric icon={Clock3} label="متوسط التأخير" value={`${model.avgDelay} د`} note="لكل رحلة مكتملة" /><Metric icon={Users} label="أكثر محطة نشاطًا" value={name(model.busiest)} note="حسب متوسط الصاعدين" /></div><div className="platform-grid operations-grid"><Section title="أسباب التأخير"><div className="delay-bars">{totals.map((item) => <div key={item.cause}><span>{delayText[item.cause]}</span><i><b style={{ width: `${Math.round(item.amount / total * 100)}%` }} /></i><em>{Math.round(item.amount / total * 100)}%</em></div>)}</div></Section><Section title="حالة التشغيل"><div className="operations-note"><Radio size={21} /><div><b>الخط B12 تحت المراقبة</b><p>{requests.length} طلب صعود في المنصة. تتم مزامنة الطلبات مع مساحة السائق والمحطة.</p></div></div></Section></div></>; }
