import { useEffect, useMemo, useState } from "react";
import { Accessibility, ArrowLeft, Bell, BusFront, Check, CheckCircle2, CircleAlert, Clock3, LogOut, MapPin, Radio, Route, Send, ShieldCheck, Ticket, UserRound, Users } from "lucide-react";

const API = "http://127.0.0.1:8000/api";
const labels = { rider: "فرد", driver: "سائق", station: "موظف محطة", ops: "مشرف تشغيل" };
const stopLabels = { "North Station": "المحطة الشمالية", "Market Street": "شارع السوق", "Central Hospital": "المستشفى المركزي", "University Gate": "بوابة الجامعة", "Civic Center": "المركز المدني" };
const stopName = (stop) => stopLabels[stop?.stop_name] || stop?.stop_name || "-";
const api = async (path, options) => { const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json" }, ...options }); const result = await response.json(); if (!response.ok) throw new Error(result.detail || "تعذر إتمام الطلب."); return result; };

function Login({ onLogin }) {
  const [role, setRole] = useState("rider"), [id, setId] = useState("1023456789"), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const choices = [["rider", UserRound, "الراكب", "خدمات الرحلات وطلبات الصعود"], ["driver", BusFront, "السائق", "خطة الرحلة وطلبات الركاب"], ["station", MapPin, "المحطة", "لوحة المغادرات وخدمة المسافرين"], ["ops", Route, "التشغيل", "متابعة الخطوط والقرارات التشغيلية"]];
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { onLogin(await api("/auth/login", { method: "POST", body: JSON.stringify({ national_id: id, role }) })); } catch (failure) { setError(failure.message); } finally { setBusy(false); } };
  return <div className="product-login" dir="rtl"><div className="login-shell"><aside className="login-aside"><div className="product-brand"><span><Route size={28} /></span><div><strong>مسار</strong><small>MASAR</small></div></div><div className="login-message"><span>منصة النقل الحضري</span><h1>خدماتك في رحلة واحدة.</h1><p>منصة موحدة تربط الراكب والسائق والمحطة ومركز التشغيل على بيانات تشغيل مشتركة.</p></div><div className="login-trust"><ShieldCheck size={18} /><span>بيئة محلية آمنة للتشغيل والتجربة</span></div></aside><main className="login-main"><div className="login-heading"><span>تسجيل الدخول</span><h2>مرحبًا بك في مسار</h2><p>اختر صفتك للوصول إلى الخدمات المناسبة لك.</p></div><form onSubmit={submit}><div className="role-choices">{choices.map(([key, Icon, title, text]) => <button type="button" onClick={() => setRole(key)} className={role === key ? "chosen" : ""} key={key}><Icon size={20} /><div><b>{title}</b><span>{text}</span></div><i>{role === key && <Check size={14} />}</i></button>)}</div><label className="login-field"><span>رقم الهوية الوطنية / الإقامة</span><input value={id} maxLength="10" inputMode="numeric" onChange={(e) => setId(e.target.value.replace(/\D/g, ""))} /></label>{error && <p className="login-error"><CircleAlert size={16} />{error}</p>}<button className="login-submit" disabled={busy}>{busy ? "جارِ التحقق..." : "دخول آمن"}<ArrowLeft size={17} /></button><p className="login-footnote">هذه البيئة مرتبطة بواجهة دخول محلية. في الإنتاج تُستبدل بخدمة النفاذ الوطني الموحد.</p></form></main></div></div>;
}

function RouteMap({ stops, selected }) { return <div className="route-map"><img src="/assets/eastern-region-bus-map.png" alt="خريطة شبكة حافلات المنطقة الشرقية" />{stops.map((stop, index) => <div className={`map-stop ${index === selected ? "active" : ""}`} style={{ left: `${27 + index * 10}%`, top: `${68 - index * 6}%` }} key={stop.stop_id}><i /><span>{stopName(stop)}</span></div>)}<div className="map-bus" style={{ left: `${30 + selected * 10}%`, top: `${65 - selected * 6}%` }}><BusFront size={17} /></div><div className="map-label"><Radio size={13} /> شبكة حافلات المنطقة الشرقية</div></div> }

function AppShell({ user, transit, bookings, refresh, onLogout }) {
  const [view, setView] = useState("home"); const profile = user.role;
  const nav = profile === "rider" ? [["home", "الرئيسية"], ["booking", "طلب صعود"], ["tickets", "طلباتي"]] : profile === "driver" ? [["home", "لوحة الرحلة"], ["requests", "طلبات الركاب"]] : profile === "station" ? [["home", "لوحة المحطة"], ["requests", "طلبات الخدمة"]] : [["home", "المتابعة"], ["requests", "الطلبات"]];
  return <div className="product-app" dir="rtl"><header className="product-header"><div className="header-brand"><span><Route size={20} /></span><b>مسار</b></div><nav>{nav.map(([key, label]) => <button className={view === key ? "current" : ""} onClick={() => setView(key)} key={key}>{label}</button>)}</nav><div className="account"><Bell size={18} /><span className="account-avatar">{user.name[0]}</span><div><b>{user.name}</b><small>{labels[user.role]}</small></div><button aria-label="تسجيل الخروج" onClick={onLogout}><LogOut size={17} /></button></div></header><main className="product-main">{view === "home" && <Home user={user} transit={transit} bookings={bookings} setView={setView} />}{view === "booking" && <Booking user={user} transit={transit} refresh={refresh} />}{view === "tickets" && <Tickets bookings={bookings} transit={transit} />}{view === "requests" && <Requests user={user} transit={transit} bookings={bookings} refresh={refresh} />}</main></div>;
}

function Home({ user, transit, bookings, setView }) { if (user.role === "ops") return <OperationsDashboard transit={transit} bookings={bookings} />; const event = transit.events[1], open = bookings.filter((item) => ["pending", "accepted"].includes(item.status)); return <><section className="product-welcome"><div><span>الهيئة السعودية للنقل</span><h1>{user.role === "rider" ? `أهلًا ${user.name}` : "مرحبًا بك في منصة مسار"}</h1><p>{user.role === "rider" ? "اطلب الصعود وتابع رحلتك من مكان واحد." : "متابعة موحدة لخط B12 وطلبات المسافرين في الوقت الفعلي."}</p></div><div className="service-state"><CheckCircle2 size={17} /><b>جميع الخدمات متاحة</b><small>آخر تحديث الآن</small></div></section><div className="product-kpis"><Kpi icon={Clock3} label="الرحلة التالية" value={clock(transit.trip.departure_time, event.actual_arrival_min)} note="من شارع السوق" /><Kpi icon={BusFront} label="حالة الخط" value="منتظم" note="B12 · 5 محطات" /><Kpi icon={Users} label={user.role === "rider" ? "طلباتي النشطة" : "طلبات نشطة"} value={open.length} note="متصلة بخدمة الحجز" /></div><section className="map-card"><div className="card-title"><div><span>المسار المباشر</span><h2>خط B12: المحطة الشمالية إلى المركز المدني</h2></div>{user.role === "rider" && <button className="product-action" onClick={() => setView("booking")}>طلب صعود <ArrowLeft size={15} /></button>}</div><RouteMap stops={transit.stops} selected={1} /><div className="map-summary"><span><i className="dot green" />الباص عند شارع السوق</span><span><i className="dot amber" />تأخير تراكمي دقيقتان</span><span>السعة المتاحة: {transit.route.bus_capacity - transit.events[1].passenger_load} مقعد</span></div></section></> }

function OperationsDashboard({ transit, bookings }) {
  const average = (items, key) => items.reduce((sum, item) => sum + +item[key], 0) / Math.max(items.length, 1);
  const onTime = Math.round(transit.trips.filter((trip) => +trip.final_delay_sec <= 180).length / transit.trips.length * 100);
  const peak = Math.round(average(transit.trips.filter((trip) => trip.is_peak === "True"), "final_delay_sec") / 60);
  const offPeak = Math.round(average(transit.trips.filter((trip) => trip.is_peak !== "True"), "final_delay_sec") / 60);
  const active = bookings.filter((booking) => ["pending", "accepted"].includes(booking.status)).length;
  const causes = ["traffic", "boarding", "schedule_gap"].map((cause) => ({ cause, total: transit.stop_events.filter((event) => event.delay_cause === cause).reduce((sum, event) => sum + +event.added_delay_sec, 0) }));
  const totalDelay = causes.reduce((sum, item) => sum + item.total, 0);
  const stops = transit.stops.map((stop) => { const events = transit.stop_events.filter((event) => event.stop_id === stop.stop_id); return { stop, board: average(events, "passengers_boarding"), dwell: average(events, "dwell_excess_sec") }; });
  return <section className="operations-dashboard"><div className="product-welcome"><div><span>مركز التحكم الحضري</span><h1>لوحة أداء خط B12</h1><p>مؤشرات تشغيلية مبنية على كامل سجلات الرحلات وفعاليات التوقف، مع متابعة مباشرة لطلبات الركاب.</p></div><div className="service-state"><Radio size={17} /><b>تحديث تشغيلي مباشر</b><small>{transit.trips.length} رحلة مسجلة</small></div></div><div className="ops-kpis"><Kpi icon={CheckCircle2} label="الالتزام بالمواعيد" value={`${onTime}%`} note="تأخير 3 دقائق أو أقل" /><Kpi icon={Clock3} label="متوسط التأخير" value={`${Math.round(average(transit.trips, "final_delay_sec") / 60)} د`} note="لكل رحلة مكتملة" /><Kpi icon={Clock3} label="تأخير الذروة" value={`${peak} د`} note={`خارج الذروة ${offPeak} د`} /><Kpi icon={Users} label="طلبات نشطة" value={active} note={`${bookings.length} طلب محفوظ`} /><Kpi icon={BusFront} label="سعة الخط" value={transit.route.bus_capacity} note="راكب لكل باص" /></div><div className="ops-grid"><section className="map-card"><div className="card-title"><div><span>الموقع التشغيلي</span><h2>تتبع الرحلة المعروضة</h2></div><small>الرحلة {transit.trip.trip_id}</small></div><RouteMap stops={transit.stops} selected={1} /><div className="map-summary"><span><i className="dot green" />الباص عند شارع السوق</span><span>حمولة حالية: {transit.events[1].passenger_load} راكب</span></div></section><section className="ops-panel"><div className="card-title"><div><span>أسباب التأخير</span><h2>الدقائق المضافة</h2></div></div><div className="ops-bars">{causes.map((item) => <div key={item.cause}><span>{{ traffic: "الازدحام المروري", boarding: "صعود الركاب", schedule_gap: "فجوة الجدول" }[item.cause]}</span><i><b style={{ width: `${Math.round(item.total / totalDelay * 100)}%` }} /></i><em>{Math.round(item.total / totalDelay * 100)}%</em></div>)}</div><div className="ops-action"><CircleAlert size={18} /><div><b>تنبيه تشغيل</b><span>{active ? `${active} طلب ركاب يحتاج متابعة من السائقين.` : "لا توجد طلبات ركاب معلقة."}</span></div></div></section></div><section className="ops-table"><div className="card-title"><div><span>أداء المحطات</span><h2>المؤشرات حسب محطة التوقف</h2></div></div><div className="ops-table-head"><span>المحطة</span><span>متوسط الصاعدين</span><span>توقف إضافي</span><span>الحالة</span></div>{stops.map((item) => <div className="ops-table-row" key={item.stop.stop_id}><b>{stopName(item.stop)}</b><span>{item.board.toFixed(1)} راكب</span><span>{item.dwell.toFixed(0)} ثانية</span><em className={item.dwell > 25 ? "high" : item.dwell > 12 ? "medium" : "good"}>{item.dwell > 25 ? "مرتفع" : item.dwell > 12 ? "متابعة" : "مستقر"}</em></div>)}</section></section>;
}
function Kpi({ icon: Icon, label, value, note }) { return <article className="product-kpi"><span><Icon size={18} /></span><div><small>{label}</small><b>{value}</b><em>{note}</em></div></article> }
function Booking({ user, transit, refresh }) { const [form, setForm] = useState({ origin: "2", destination: "5", count: "1", assistance: false, payment: "mada" }), [message, setMessage] = useState(""), [pending, setPending] = useState(false); const update = (key, value) => setForm((current) => ({ ...current, [key]: value })); const submit = async (event) => { event.preventDefault(); setPending(true); setMessage(""); try { const booking = await api("/bookings", { method: "POST", body: JSON.stringify({ rider_id: user.user_id, rider_name: user.name, trip_id: transit.trip.trip_id, origin_sequence: +form.origin, destination_sequence: +form.destination, passenger_count: +form.count, assistance: form.assistance, payment_method: form.payment }) }); setMessage(`تم تسجيل الطلب ${booking.id}. يصل الباص خلال ${booking.eta_minutes} دقائق.`); await refresh(); } catch (failure) { setMessage(failure.message); } finally { setPending(false); } }; return <section className="service-layout"><div className="service-form"><span>خدمة النقل الحضري</span><h1>طلب صعود</h1><p>يرسل طلبك مباشرة إلى قائمة السائق للمراجعة والقبول.</p><form onSubmit={submit}><div className="input-grid"><Field label="محطة الانطلاق"><select value={form.origin} onChange={(e) => update("origin", e.target.value)}>{transit.stops.map((stop) => <option value={stop.sequence} key={stop.stop_id}>{stopName(stop)}</option>)}</select></Field><Field label="الوجهة"><select value={form.destination} onChange={(e) => update("destination", e.target.value)}>{transit.stops.map((stop) => <option value={stop.sequence} key={stop.stop_id}>{stopName(stop)}</option>)}</select></Field><Field label="عدد الركاب"><input type="number" min="1" max="8" value={form.count} onChange={(e) => update("count", e.target.value)} /></Field></div><div className="payment-choice"><span>طريقة الدفع</span><div>{[["mada", "مدى"], ["apple_pay", "Apple Pay"], ["card", "بطاقة"], ["on_board", "عند الصعود"]].map(([value, label]) => <label className={form.payment === value ? "picked" : ""} key={value}><input type="radio" name="payment" value={value} checked={form.payment === value} onChange={(e) => update("payment", e.target.value)} />{label}</label>)}</div></div><label className="product-checkbox"><input type="checkbox" checked={form.assistance} onChange={(e) => update("assistance", e.target.checked)} /><Accessibility size={17} />أحتاج مساعدة أو أولوية عند الصعود</label><button className="login-submit" disabled={pending}>{pending ? "جارِ إرسال الطلب..." : "تأكيد طلب الصعود"}<Send size={17} /></button>{message && <p className={message.startsWith("تم") ? "booking-message okay" : "booking-message bad"}>{message}</p>}</form></div><aside className="service-info"><Ticket size={27} /><h2>كيف تعمل الخدمة؟</h2><ol><li>اختر محطتك ووجهتك.</li><li>يصل الطلب إلى السائق فورًا.</li><li>تابع حالة الطلب من صفحة طلباتي.</li></ol><p><ShieldCheck size={15} />يتم حفظ اختيار الدفع مع طلب الرحلة، دون تخزين بيانات بطاقتك.</p></aside></section> }
function Field({ label, children }) { return <label className="product-field"><span>{label}</span>{children}</label> }
function Tickets({ bookings, transit }) { return <section><div className="page-heading"><span>خدماتي</span><h1>طلباتي</h1></div>{bookings.length ? <div className="ticket-list">{bookings.map((booking) => <article key={booking.id}><div className="ticket-route"><b>{stopName(transit.stops[booking.origin_sequence - 1])}</b><ArrowLeft size={15} /><b>{stopName(transit.stops[booking.destination_sequence - 1])}</b></div><div><small>{booking.id} · {booking.passenger_count} راكب · {booking.fare_sar} ر.س</small>{booking.assistance ? <em><Accessibility size={13} />مساعدة مطلوبة</em> : null}</div><span className={`booking-status ${booking.status}`}>{statusText(booking.status)}</span>{booking.driver_note && <p>رسالة السائق: {booking.driver_note}</p>}</article>)}</div> : <Empty text="لا توجد طلبات مسجلة. يمكنك إنشاء طلب صعود جديد الآن." />}</section> }
function Requests({ user, transit, bookings, refresh }) { const [notes, setNotes] = useState({}); const update = async (booking, status) => { try { await api(`/bookings/${booking.id}`, { method: "PATCH", body: JSON.stringify({ status, driver_note: notes[booking.id] || "", actor_role: user.role }) }); await refresh(); } catch (failure) { window.alert(failure.message); } }; return <section><div className="page-heading"><span>{user.role === "driver" ? "إدارة الرحلة" : "خدمات المحطة والتشغيل"}</span><h1>طلبات الركاب</h1><p>هذه قائمة مشتركة ومباشرة. أي قرار يتم حفظه في قاعدة بيانات الخدمة ويظهر للراكب فور التحديث.</p></div>{bookings.length ? <div className="request-table">{bookings.map((booking) => <article key={booking.id}><div className="request-user"><span>{booking.rider_name[0]}</span><div><b>{booking.rider_name}</b><small>{booking.id} · {booking.passenger_count} راكب</small></div></div><div><b>{stopName(transit.stops[booking.origin_sequence - 1])}</b><small>إلى {stopName(transit.stops[booking.destination_sequence - 1])}</small></div><div>{booking.assistance && <em className="assistance"><Accessibility size={14} />مساعدة مطلوبة</em>}<small>الوصول المتوقع {booking.eta_minutes} د</small></div><div className="request-decision">{booking.status === "pending" && user.role === "driver" ? <><input placeholder="ملاحظة للسائق (اختياري)" value={notes[booking.id] || ""} onChange={(e) => setNotes({ ...notes, [booking.id]: e.target.value })} /><button className="approve" onClick={() => update(booking, "accepted")}>قبول</button><button className="decline" onClick={() => update(booking, "declined")}>اعتذار</button></> : <span className={`booking-status ${booking.status}`}>{statusText(booking.status)}</span>}{booking.status === "accepted" && user.role === "driver" && <button className="boarded" onClick={() => update(booking, "boarded")}>تم الصعود</button>}</div></article>)}</div> : <Empty text="لا توجد طلبات ركاب في الوقت الحالي." />}</section> }
function Empty({ text }) { return <div className="empty-service"><Ticket size={28} /><p>{text}</p></div> }
const statusText = (status) => ({ pending: "بانتظار مراجعة السائق", accepted: "تم قبول الطلب", declined: "تم الاعتذار", boarded: "تم الصعود" }[status] || status);
const clock = (date, add) => { const value = new Date(date); value.setMinutes(value.getMinutes() + Number(add)); return value.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" }); };

export default function MasarProduct() { const [user, setUser] = useState(() => { try { return JSON.parse(sessionStorage.getItem("masar-user")); } catch { return null; } }); const [transit, setTransit] = useState(null); const [bookings, setBookings] = useState([]); const [error, setError] = useState(""); const refresh = async (currentUser = user) => { if (!currentUser) return; try { const list = await api(currentUser.role === "rider" ? `/bookings?rider_id=${currentUser.user_id}` : "/bookings"); setBookings(list.bookings); } catch (failure) { setError(failure.message); } }; useEffect(() => { api("/transit").then((data) => { data.stops.sort((a, b) => +a.sequence - +b.sequence); data.trips.sort((a, b) => new Date(a.departure_time) - new Date(b.departure_time)); data.route = data.routes[0]; const trip = data.trips[Math.floor(data.trips.length / 2)]; data.trip = trip; data.events = data.stop_events.filter((event) => event.trip_id === trip.trip_id).sort((a, b) => +a.sequence - +b.sequence); setTransit(data); }).catch((failure) => setError(failure.message)); }, []); useEffect(() => { refresh(); const id = window.setInterval(() => refresh(), 5000); return () => window.clearInterval(id); }, [user]); const login = (profile) => { sessionStorage.setItem("masar-user", JSON.stringify(profile)); setUser(profile); }; const logout = () => { sessionStorage.removeItem("masar-user"); setUser(null); setBookings([]); }; if (error) return <div className="product-state"><CircleAlert size={30} /><h1>تعذر الاتصال بخدمات مسار</h1><p>{error}</p></div>; if (!transit) return <div className="product-state"><Radio className="spin" size={30} /><p>يتم الاتصال بخدمات مسار...</p></div>; return user ? <AppShell user={user} transit={transit} bookings={bookings} refresh={refresh} onLogout={logout} /> : <Login onLogin={login} />; }
